name: build-and-publish
on:
  push:
    branches: 
      - main
    tags:
      - "v0.1.2"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.8
        with:
          python_version: "3.8.10"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          ignore_dev_requirements: "yes"